# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]

[[constraint]]
  name = "github.com/cncd/pipeline"
  branch = "master"

[[constraint]]
  name = "github.com/drone/drone-go"
  revision = "dd0a126edb93bbff0df4d0c5deaba3aa70f0f931"

[[constraint]]
  branch = "master"
  name = "github.com/drone/envsubst"

[[constraint]]
  branch = "master"
  name = "github.com/jackspirou/syscerts"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/browser"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-jsonnet"
  source = "https://github.com/drone/go-jsonnet.git"

#
# Some project dependencies hale from the dark ages
# of Go dependnecy management and require that we point
# to specific revisions.
#

[[override]]
  name = "github.com/docker/docker"
  revision = "f645ffca04abf2dd6c89ac9057a1eb7d2b0ac338"

[[override]]
  name = "github.com/docker/distribution"
  revision = "7dba427612198a11b161a27f9d40bb2dca1ccd20"

[[override]]
  name = "github.com/docker/go-connections"
  revision = "eb315e36415380e7c2fdee175262560ff42359da"

[[override]]
  name = "github.com/docker/go-units"
  revision = "f2145db703495b2e525c59662db69a7344b00bb8"

[[override]]
  name = "github.com/docker/libcompose"
  revision = "1c4bd4542afb20db0b51afd71d9ebceaf206e2dd"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
