# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/docker/go-units"
  version = "0.3.3"

[[constraint]]
  branch = "master"
  name = "github.com/drone/drone-go"

[[constraint]]
  branch = "master"
  name = "github.com/drone/drone-runtime"

[[constraint]]
  name = "github.com/drone/drone-yaml"
  branch = "master"

[[constraint]]
  name = "github.com/drone/signal"
  version = "1.0.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/google/go-jsonnet"
  version = "0.11.2"

[[constraint]]
  branch = "master"
  name = "github.com/jackspirou/syscerts"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/browser"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[prune]
  go-tests = true
  unused-packages = true
